#!bin/bash
#only works in glitch.com or, where this is produced at
jsdoc -c jsdoc.json *
rm -rf ~/docs/0.*
rm -rf ~/docs/out
rm -rf ~/docs/forge*
cp -r ~/out/forge-remote-manager/0.0.5-beta ~/docs
rm -rf out
if [ $1 = '--no-refresh' ]
then
  exit 0
else
  refresh
  exit 0
fi