#!bin/bash
#only works in glitch.com or, where this is produced at
jsdoc -c jsdoc.json .
rm -rf ~/docs/out
cp -r ~/out ~/docs
rm -rf out
if [ $1 = '--no-refresh' ]
then
  exit 0
else
  refresh
  exit 0
fi